# network architecture
# encoder related
encoder: conformer
encoder_conf:
    output_size: 512    # dimension of attention
    attention_heads: 8
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder input type, you can chose conv2d, conv2d6 and conv2d8
    normalize_before: true
    cnn_module_kernel: 31
    use_cnn_module: True
    # causal: true
    # use_dynamic_chunk: true
    cnn_module_norm: 'layer_norm'
    activation_type: 'swish'
    pos_enc_layer_type: 'rel_pos'
    selfattention_layer_type: 'rwkv_tmix60_bidirectional' # rel_selfattn rwkv_tmix60 rwkv_tmix60_bidirectional rwkv_tmix70 mamba_att
    rnn_att_version: 'rwkv' # rwkv rwkv7 mamba mamba2
    rnn_att_direction: 'bi' # uni bi
    rwkv_ctx_len:  2048
    rwkv_do_bfloat16:  True

# decoder related
decoder: none
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 3
    r_num_blocks: 3
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

tokenizer: rev_bpe
tokenizer_conf:
  #symbol_table_path: 'data/lang_char_XL/train_xl_unigram5000_units.txt'
  symbol_table_path: '/shared/jp/up.rev-wenet/examples/gigaspeech/s0/gigaspeech_cmvn_and_tok/units.txt'
  #symbol_table_path: '/shared/natalie/rev-wenet/examples/rev/s0/exp/tokenizers/tok_fixbracket_100khr_unigram_10000_8/tk.units.txt'
  split_with_space: false
  #bpe_path: 'data/lang_char_XL/train_xl_unigram5000.model'
  bpe_path: '/shared/jp/up.rev-wenet/examples/gigaspeech/s0/gigaspeech_cmvn_and_tok/train_xl_unigram5000.model'
  #bpe_path: '/shared/natalie/rev-wenet/examples/rev/s0/exp/tokenizers/tok_fixbracket_100khr_unigram_10000_8/tk.model'
  non_lang_syms_path: null
  is_multilingual: false
  num_languages: 1
  special_tokens:
    <blank>: 0
    <unk>: 1
    <sos>: 2
    <eos>: 2

ctc: ctc
ctc_conf:
  ctc_blank_id: 0

#cmvn: global_cmvn
#cmvn_conf:
#  cmvn_file: 'data/train_xl/global_cmvn'
#  is_json_cmvn: true
cmvn: global_cmvn
cmvn_conf:
    #cmvn_file: /shared/natalie/rev-wenet/examples/rev/s0/en-cmvn.json
    cmvn_file: '/shared/jp/up.rev-wenet/examples/gigaspeech/s0/gigaspeech_cmvn_and_tok/global_cmvn'
    is_json_cmvn: true

# # hybrid CTC/attention
# model: asr_model
# model_conf:
#     ctc_weight: 0.3
#     reverse_weight: 0.3
#     lsm_weight: 0.1     # label smoothing option
#     length_normalized_loss: false

#joint_conf:
#    enc_output_size: 512
#    pred_output_size: 640
#    join_dim: 640
#    prejoin_linear: True
#    postjoin_linear: false
#    joint_mode: 'add'
#    activation: 'tanh'
#
#predictor: rnn
#predictor_conf:
#    embed_size: 640
#    output_size: 640
#    embed_dropout: 0.1
#    hidden_size: 640
#    num_layers: 2
#    bias: true
#    rnn_type: 'lstm'
#    dropout: 0.1

# hybrid transducer+ctc+attention
#model: transducer
model: asr_model
model_conf:
    #transducer_weight: 0.3 #0.75
    ctc_weight: 1
    #attention_weight: 0.5 #0.15
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false
    #reverse_weight: 0.3
    #
restrict_learning:
    - exclude: '.*'    
    - include: '.*rwkv_wrapper.*'    


dataset: asr
dataset_conf:
    uppercase: True
    merge_utterances: True
    merge_utterances_conf:
        min_audio_len_acceptable_secs: 0.3
        #min_audio_len_secs: 190
        #max_audio_len_secs: 200
        min_audio_len_secs: 75
        max_audio_len_secs: 85
        add_sw_tag: false
        enable_after_epoch: -1
    filter_conf:
        max_length: 50000
        min_length: 1000
        token_max_length: 3600
        token_min_length: 1
    resample_conf:
        resample_rate: 16000
    use_rev_tk: true
    speed_perturb: false
    fbank_conf:
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 1.0
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 3
        num_f_mask: 2
        max_t: 50
        max_f: 10
    shuffle: true
    shuffle_conf:
        shuffle_size: 50
    sort: true
    sort_conf:
        sort_size: 10  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'dynamic' # static or dynamic
        max_frames_in_batch: 20000 #15000 #25000 #20000

throw_on_early_termination: true

grad_clip: 0.1
accum_grad: 1
max_epoch: 60
log_interval: 100

optim: adam
optim_conf:
    lr: 0.0001 #0.001
scheduler: steadylr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 100000 #80000

# experiment tracking related
snapshot_saving_conf:
    #snap_every: 6000
    save_interval: 3000 
    save_optimizer_every: 10
    save_to_wandb: True
    use_named_snapshots: False
    run_tag: "run_tag"
